### ISSUE TITLE
Submit abell grammer to github 

### ISSUE THREAD

**Issue by pantharshit00** [abelljs/vscode-abell-language-features#5]
So that we can have ```abell support on GitHub :)

You have already done the hard work of creating a text mate grammar. 

We will need to make a PR to https://github.com/github/linguist

**Comment by saurabhdaware** [comment]
Yes I saw this earlier but according to contribution guide
> We try only to add new extensions once they have some usage on GitHub. In most cases we prefer that extensions be in use in hundreds of repositories before supporting them in Linguist.

So we will have to wait until .abell files are commonly used in repositories

**Comment by pantharshit00** [comment]
Ohh, we already had a good at prisma so our PR good accepted.

Yeah, we can wait for now.

**Comment by saurabhdaware** [comment]
I think I will remember to do this when time comes so good to close this issue for now.
