### ISSUE TITLE
Publish extension to open-vsx.org

### ISSUE THREAD

**Issue by pantharshit00** [abelljs/vscode-abell-language-features#6]
Many forks of vscode like Code OSS which removes microsoft telemetry uses this extension registry as microsoft doesn't allow you to incoperate the official registry in any other editor.

I think we should also publish this extenion to https://open-vsx.org/ so that it is also accessible for those people.

I hit this when I was using oni2 editor.

**Comment by saurabhdaware** [comment]
Its published on open-vsx now https://open-vsx.org/extension/saurabh/abell-language-features 🎉 

This also makes it work with Stackblitz Codeflow
